# -*- coding: utf-8 -*-
"""ML1 Final Exam 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubgY755Aso2XUDMXFoo0i7cDFMPbhWY3
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time

def main():
    response = requests.get("https://www.yelp.ca/biz/pai-northern-thai-kitchen-toronto-5?osq=Restaurants")

    soup = BeautifulSoup(response.text, 'html.parser')

    # Extract Restaurant Name
    name_tag = soup.find('h1', class_='y-css-olzveb')
    restaurant_name = name_tag.text.strip() if name_tag else "Not Found"

    # Extract Total Reviews Count
    reviews_count_tag = soup.find('span', class_='y-css-yrt0i5')
    reviews_count = reviews_count_tag.text.strip() if reviews_count_tag else "Not Found"
    reviews_count = re.sub(r'[^0-9]', '', reviews_count)  # Extract numerical value only

    # Extract Reviews
    reviews_data = []
    review_blocks = soup.find_all('p', class_='comment__09f24__D0cxf')
    reviewers = soup.find_all('a', class_='y-css-1x1e1r2')
    ratings = soup.find_all('path', attrs={"fill": "rgba(251,67,60,1)"})

    print(restaurant_name)
    print(reviews_count)
    print(reviewers)
    print(ratings)

    for i in range(min(len(review_blocks), len(reviewers), len(ratings))):
            review_text = review_blocks[i].find('span', class_='raw__09f24__T4Ezm')
            review_text = review_text.text.strip() if review_text else "No review text"

            reviewer = reviewers[i].text.strip() if reviewers[i] else "Anonymous"

            rating = "5"  # Assuming all extracted ratings are full stars (5 stars)

            reviews_data.append([reviewer, review_text, rating])

    print(reviews_data)

    # Save to CSV
    df = pd.DataFrame(reviews_data, columns=["Reviewer", "Review Text", "Rating"])
    csv_filename = f"{restaurant_name.replace(' ', '_')}_reviews.csv"
    df.to_csv(csv_filename, index=False, encoding='utf-8')

    print(f"Data saved to {csv_filename}")


if __name__ == "__main__":
    main()