# -*- coding: utf-8 -*-
"""Face_Detection_Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taP-_boqfizq6WXSYu72WSlO3HTlab8Q
"""

import cv2
import os

# 載入 Haar cascade 模型
cascPathface = os.path.dirname(cv2.__file__) + "/data/haarcascade_frontalface_alt2.xml"
cascPatheyes = os.path.dirname(cv2.__file__) + "/data/haarcascade_eye_tree_eyeglasses.xml"

faceCascade = cv2.CascadeClassifier(cascPathface)
eyeCascade = cv2.CascadeClassifier(cascPatheyes)

# 啟動攝影機
video_capture = cv2.VideoCapture(0)

if not video_capture.isOpened():
    print("Error: Cannot access webcam.")
    exit()

while True:
    # 擷取影像畫面
    ret, frame = video_capture.read()

    if not ret:
        print("Error: Failed to grab frame.")
        break

    # 轉為灰階
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 偵測人臉
    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(60, 60),
        flags=cv2.CASCADE_SCALE_IMAGE
    )

    for (x, y, w, h) in faces:
        # 畫出人臉矩形
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 255, 0), 2)
        faceROI = frame[y:y + h, x:x + w]

        # 偵測眼睛
        eyes = eyeCascade.detectMultiScale(faceROI)
        for (x2, y2, w2, h2) in eyes:
            eye_center = (x + x2 + w2 // 2, y + y2 + h2 // 2)
            radius = int(round((w2 + h2) * 0.25))
            frame = cv2.circle(frame, eye_center, radius, (0, 0, 255), 4)

        # 顯示臉部區域（避免在未偵測臉時報錯）
        if faceROI is not None and faceROI.size > 0:
            cv2.imshow("Face ROI", faceROI)

    # 顯示完整畫面
    cv2.imshow('Face Video', frame)

    # 按下 'q' 鍵離開
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 清理資源
video_capture.release()
cv2.destroyAllWindows()